package com.smylay.hr.model;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;
// This is an entity class automatically generated by java that allows the system to access and interact with my database table Holidays.

@Entity
@Table(name = "holidays")
@XmlRootElement
@NamedQueries({
    @NamedQuery(name = "Holidays.findAll", query = "SELECT h FROM Holidays h")
    , @NamedQuery(name = "Holidays.findByHolidayid", query = "SELECT h FROM Holidays h WHERE h.holidayid = :holidayid")
    , @NamedQuery(name = "Holidays.findByDate", query = "SELECT h FROM Holidays h WHERE h.date = :date")
    , @NamedQuery(name = "Holidays.findByName", query = "SELECT h FROM Holidays h WHERE h.name = :name")})
public class Holidays implements Serializable {

    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Basic(optional = false)
    @Column(name = "holidayid")
    private Integer holidayid;
    @Column(name = "date")
    @Temporal(TemporalType.TIMESTAMP)
    private Date date;
    @Size(max = 200)
    @Column(name = "name")
    private String name;

    public Holidays() {
    }

    public Holidays(Integer holidayid) {
        this.holidayid = holidayid;
    }

    public Integer getHolidayid() {
        return holidayid;
    }

    public void setHolidayid(Integer holidayid) {
        this.holidayid = holidayid;
    }

    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (holidayid != null ? holidayid.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        if (!(object instanceof Holidays)) {
            return false;
        }
        Holidays other = (Holidays) object;
        if ((this.holidayid == null && other.holidayid != null) || (this.holidayid != null && !this.holidayid.equals(other.holidayid))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "com.smylay.hr.Holidays[ holidayid=" + holidayid + " ]";
    }

}
