package com.smylay.hr.model;

import java.io.Serializable;
import java.util.Collection;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;
// This is an entity class automatically generated by java that allows the system to access and interact with my database table Reason.

@Entity
@Table(name = "reason")
@XmlRootElement
@NamedQueries({
    @NamedQuery(name = "Reason.findAll", query = "SELECT r FROM Reason r")
    , @NamedQuery(name = "Reason.findByReasonid", query = "SELECT r FROM Reason r WHERE r.reasonid = :reasonid")
    , @NamedQuery(name = "Reason.findByName", query = "SELECT r FROM Reason r WHERE r.name = :name")})
public class Reason implements Serializable {

    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Basic(optional = false)
    @Column(name = "reasonid")
    private Integer reasonid;
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 45)
    @Column(name = "name")
    private String name;
    @OneToMany(cascade = CascadeType.ALL, mappedBy = "reasonid")
    private Collection<Absence> absenceCollection;

    public Reason() {
    }

    public Reason(Integer reasonid) {
        this.reasonid = reasonid;
    }

    public Reason(Integer reasonid, String name) {
        this.reasonid = reasonid;
        this.name = name;
    }

    public Integer getReasonid() {
        return reasonid;
    }

    public void setReasonid(Integer reasonid) {
        this.reasonid = reasonid;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @XmlTransient
    public Collection<Absence> getAbsenceCollection() {
        return absenceCollection;
    }

    public void setAbsenceCollection(Collection<Absence> absenceCollection) {
        this.absenceCollection = absenceCollection;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (reasonid != null ? reasonid.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Reason)) {
            return false;
        }
        Reason other = (Reason) object;
        if ((this.reasonid == null && other.reasonid != null) || (this.reasonid != null && !this.reasonid.equals(other.reasonid))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "com.smylay.hr.model.Reason[ reasonid=" + reasonid + " ]";
    }

}
